# Generated by Django 4.2.1 on 2023-05-28 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='usuario',
        ),
    ]

