# Generated by Django 4.2.1 on 2023-05-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBase', '0002_remove_libro_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.CharField(choices=[('aventura', 'Aventura'), ('deportes', 'Deportes'), ('estrategia', 'Estrategia'), ('cienciaficcion', 'Cienciaficcion'), ('hadas', 'Hadas'), ('gotica', 'Gotica'), ('policial', 'Policial'), ('guerra', 'Guerra'), ('paranormal', 'Paranormal'), ('fantastica', 'Fantastica'), ('autobiografia', 'Autobiografia'), ('detective', 'Detective'), ('educativa', 'Educativa'), ('humor', 'Humor'), ('infantil', 'Infantil'), ('juvenil', 'Juvenil'), ('thriller', 'Thriller'), ('viajes', 'Viajes'), ('ingenio', 'Ingenio'), ('agricultura', 'Agricultura'), ('botanica', 'Botanica'), ('juegos', 'Juegos'), ('recetas', 'Recetas')], max_length=255),
        ),
    ]

