# Generated by Django 4.2.1 on 2023-05-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBase', '0004_tema_comentario'),
    ]

    operations = [
    ]
